# Generated by Django 3.2.9 on 2021-11-23 00:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('banktd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DadosAgencia',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeAgencia', models.CharField(max_length=150)),
                ('NumAgencia', models.IntegerField()),
                ('EstadoAgencia', models.CharField(max_length=150)),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DadosTipoConta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('NomeTipoConta', models.CharField(max_length=50)),
                ('NumTipoConta', models.IntegerField()),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='cadusuario',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CadContaUsuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Agencia', models.IntegerField()),
                ('Conta', models.IntegerField()),
                ('Created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('Updated_date', models.DateTimeField(blank=True, null=True)),
                ('Tipo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banktd.dadostipoconta')),
                ('idusuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banktd.cadusuario')),
            ],
        ),
    ]
