# Generated by Django 3.2.9 on 2021-11-23 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('banktd', '0002_auto_20211122_2133'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadcontausuario',
            name='Agencia',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='banktd.dadosagencia'),
        ),
    ]
